version: '3.1'
services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: prisma
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dbnetwork
  app: 
    build:
      context: quizzeo
      args:
        - DATABASE_URL=postgresql://prisma:password@db:5432/mydb
        - SALT=secret
        - PASSWORD_SALT=10
        - NEXT_PUBLIC_API_URL=${API_URL:-http://localhost/api/}
    depends_on:
      - db
    ports:
      - 80:3000
    networks:
      - dbnetwork

volumes:
  pgdata:

networks:
  dbnetwork: